/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FinancesRouteImport } from './routes/finances'
import { Route as IndexRouteImport } from './routes/index'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancesRoute = FinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/goals': typeof GoalsRoute
  '/mood': typeof MoodRoute
  '/planner': typeof PlannerRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/goals': typeof GoalsRoute
  '/mood': typeof MoodRoute
  '/planner': typeof PlannerRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/goals': typeof GoalsRoute
  '/mood': typeof MoodRoute
  '/planner': typeof PlannerRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finances'
    | '/goals'
    | '/mood'
    | '/planner'
    | '/routines'
    | '/settings'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finances'
    | '/goals'
    | '/mood'
    | '/planner'
    | '/routines'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/finances'
    | '/goals'
    | '/mood'
    | '/planner'
    | '/routines'
    | '/settings'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancesRoute: typeof FinancesRoute
  GoalsRoute: typeof GoalsRoute
  MoodRoute: typeof MoodRoute
  PlannerRoute: typeof PlannerRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancesRoute: FinancesRoute,
  GoalsRoute: GoalsRoute,
  MoodRoute: MoodRoute,
  PlannerRoute: PlannerRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
